# Generated by Django 5.1.5 on 2025-01-21 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0005_task_is_checked_alter_task_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='task',
        ),
    ]
